import Lattice
import Foundation

/// A single stored memory with semantic embedding for vector search.
///
/// Memories are the core unit of the Engram system. Each memory stores
/// a piece of knowledge along with metadata for organization and retrieval:
///
/// - **Semantic search**: The `embedding` vector enables similarity-based recall,
///   so memories can be found by meaning rather than exact keyword match.
/// - **Project scoping**: Memories are tagged with a `project` to keep project-specific
///   knowledge separate. Use `"global"` for cross-project knowledge.
/// - **Topic categorization**: The `topic` field groups memories by category
///   (e.g., "preferences", "architecture", "debugging").
/// - **Provenance tracking**: The `source` field records where the memory originated
///   (e.g., "conversation", "code-review", a file path).
@Model @Detached
public final class Memory {
    /// The memory content — a natural-language description of the knowledge to store.
    @FullText public var content: String

    /// Category for organizing memories (e.g., "preferences", "architecture", "debugging", "patterns").
    public var topic: String

    /// Which project this memory belongs to. Use "global" for cross-project knowledge
    /// like user preferences or general patterns. Otherwise use the project name
    /// (e.g., "Lattice", "Engram").
    public var project: String

    /// Where this memory originated — provides context about how the knowledge was acquired.
    /// Examples: "conversation", "code-review", "debugging-session", or a file path.
    public var source: String

    /// Vector embedding of `content` for semantic similarity search.
    /// Generated by the paraphrase-MiniLM-L6-v2 model at storage time.
    public var embedding: Vector<Float>

    /// When this memory was created.
    public var createdAt: Date

    /// When this memory was last accessed (recalled or updated).
    public var lastAccessedAt: Date

    /// When this memory expires. Expired memories are filtered out of recall results.
    /// Defaults to `Date.distantFuture` (never expires).
    public var expiresAt: Date

    /// How many times this memory has been returned by recall. Used for frequency-based ranking boost.
    public var accessCount: Int

    /// Explicit importance rating (1-5). 0 means unset. Higher values boost recall ranking.
    public var importance: Int

    /// Whether this memory is private (excluded from group shared graphs).
    /// Private memories still sync to the user's own cloud backup. Default: false.
    ///
    /// Retract semantics: flipping this to `true` on a memory ALREADY shared
    /// with a group emits a real DELETE to the group DB (row-level filter
    /// unmatch), removing the group's copy including teammates' edits.
    /// Author-only — enforced at the MCP handler.
    public var isPrivate: Bool

    /// Who authored this memory (schema v3, Groups). Nil for legacy and
    /// never-signed-in rows. Stamped at creation from groups.json's
    /// `selfUserId`; NEVER changed by edits — attribution follows the
    /// original author, and the spoke→hub sync firewall keys on it.
    public var authorUserId: UUID?

    /// Soft-delete tombstone (schema v3, Groups). Non-nil = hidden from all
    /// recall/FTS/vector reads everywhere it syncs. Used instead of hard
    /// delete whenever the memory is group-shared; recoverable by clearing
    /// (undelete). Hard purge is an admin-only server-side operation.
    public var deletedAt: Date?

    /// Who tombstoned this memory (attribution for "tombstoned by X" notices).
    public var deletedBy: UUID?

    /// When this memory's content/metadata was last modified (schema v3).
    /// Stamped by MemoryTools on every write. Instruments how often
    /// last-arrival-wins loses newer data today, and gives field-timestamp
    /// LWW a column to compare when it lands.
    public var modifiedAt: Date?

    public init(
        content: String,
        topic: String = "general",
        project: String = "global",
        source: String = "",
        embedding: Vector<Float> = Vector<Float>([]),
        createdAt: Date = Date(),
        lastAccessedAt: Date = Date(),
        expiresAt: Date = Date.distantFuture,
        accessCount: Int = 0,
        importance: Int = 0,
        isPrivate: Bool = false,
        authorUserId: UUID? = nil,
        deletedAt: Date? = nil,
        deletedBy: UUID? = nil,
        modifiedAt: Date? = nil
    ) {
        self.content = content
        self.topic = topic
        self.project = project
        self.source = source
        self.embedding = embedding
        self.createdAt = createdAt
        self.lastAccessedAt = lastAccessedAt
        self.expiresAt = expiresAt
        self.accessCount = accessCount
        self.importance = importance
        self.isPrivate = isPrivate
        self.authorUserId = authorUserId
        self.deletedAt = deletedAt
        self.deletedBy = deletedBy
        self.modifiedAt = modifiedAt
    }
}
