import Lattice
import Foundation

/// A single stored memory with semantic embedding for vector search.
///
/// Memories are the core unit of the Engram system. Each memory stores
/// a piece of knowledge along with metadata for organization and retrieval:
///
/// - **Semantic search**: The `embedding` vector enables similarity-based recall,
///   so memories can be found by meaning rather than exact keyword match.
/// - **Project scoping**: Memories are tagged with a `project` to keep project-specific
///   knowledge separate. Use `"global"` for cross-project knowledge.
/// - **Topic categorization**: The `topic` field groups memories by category
///   (e.g., "preferences", "architecture", "debugging").
/// - **Provenance tracking**: The `source` field records where the memory originated
///   (e.g., "conversation", "code-review", a file path).
@Model @Detached
public final class Memory {
    /// The memory content — a natural-language description of the knowledge to store.
    @FullText public var content: String

    /// Category for organizing memories (e.g., "preferences", "architecture", "debugging", "patterns").
    public var topic: String

    /// Which project this memory belongs to. Use "global" for cross-project knowledge
    /// like user preferences or general patterns. Otherwise use the project name
    /// (e.g., "Lattice", "Engram").
    public var project: String

    /// Where this memory originated — provides context about how the knowledge was acquired.
    /// Examples: "conversation", "code-review", "debugging-session", or a file path.
    public var source: String

    /// Vector embedding of `content` for semantic similarity search.
    /// Generated by the paraphrase-MiniLM-L6-v2 model at storage time.
    public var embedding: Vector<Float>

    /// When this memory was created.
    public var createdAt: Date

    /// When this memory was last accessed (recalled or updated).
    public var lastAccessedAt: Date

    /// When this memory expires. Expired memories are filtered out of recall results.
    /// Defaults to `Date.distantFuture` (never expires).
    public var expiresAt: Date

    /// How many times this memory has been returned by recall. Used for frequency-based ranking boost.
    public var accessCount: Int

    /// Explicit importance rating (1-5). 0 means unset. Higher values boost recall ranking.
    public var importance: Int

    /// Whether this memory is private (excluded from team shared graphs and hive mind).
    /// Private memories still sync to the user's own cloud backup. Default: false.
    public var isPrivate: Bool

    public init(
        content: String,
        topic: String = "general",
        project: String = "global",
        source: String = "",
        embedding: Vector<Float> = Vector<Float>([]),
        createdAt: Date = Date(),
        lastAccessedAt: Date = Date(),
        expiresAt: Date = Date.distantFuture,
        accessCount: Int = 0,
        importance: Int = 0,
        isPrivate: Bool = false
    ) {
        self.content = content
        self.topic = topic
        self.project = project
        self.source = source
        self.embedding = embedding
        self.createdAt = createdAt
        self.lastAccessedAt = lastAccessedAt
        self.expiresAt = expiresAt
        self.accessCount = accessCount
        self.importance = importance
        self.isPrivate = isPrivate
    }
}
